/*
Find n'th number in a number system with only 3 and 4


Given a number system with only 3 and 4. Find the nth number in the number system. First few numbers in the number system are: 3, 4, 33, 34, 43, 44, 333, 334, 343, 344, 433, 434, 443, 444, 3333, 3334, 3343, 3344, 3433, 3434, 3443, 3444, ...
Source: Zoho Interview

We can generate all numbers with i digits using the numbers with (i-1) digits. The idea is to first add a '3' as prefix in all numbers with (i-1) digit, then add a '4'. For example, the numbers with 2 digits are 33, 34, 43 and 44. The numbers with 3 digits are 333, 334, 343, 344, 433, 434, 443 and 444 which can be generated by first adding a 3 as prefix, then 4. 

*/

#include <bits/stdc++.h>
using namespace std;

void fun(){
  
  int N = 14;
  
  vector<int> v = {3,4};
  
  if(N == 1 || N == 2){
    for(int i=0;i<N;i++){
        cout<<v[i]<<" ";
    }
  }
  
  int i = 0;
  
  while(v.size() < N){
    v.push_back(v[i]*10 + 3);
    if(v.size() < N){
      v.push_back(v[i]*10 + 4);
    }
    i++;
  }
  
  for(int i=0;i<N;i++){
    cout<<v[i]<<" ";
  }
  
  return 0;
}

// optimal solution

#include <iostream>
using namespace std;

void fun2() {
    
    int N;
    cin>>N;
    
    int power = 1;
    int ans = 0;
    
    while(N > 0){
        int res = 0;
        if(N % 2 == 0){
            res = 4 * power + ans;
        }
        else res = 3 * power + ans;
        
        ans = res;
        power *= 10;
        N = (N - 1)/2;
    }
    
    cout<<ans<<endl;
    
    return 0;
}